let mock = [{
    id: 1,
    name: "Mowich Lake",
    location: "WA",
    image: '/images/1.jpg',
    like: false,
  },
  {
    id: 2,
    name: "Strawberry Point",
    location: "WA",
    image: '/images/2.jpg',
    like: false,
  },
  {
    id: 3,
    name: "Grand Prismatic Spring",
    location: "WY",
    image: '/images/3.jpg',
    like: false,
  },
  {
    id: 4,
    name: "Delicate Arch",
    location: "UT",
    image: '/images/4.jpg',
    like: false,
  },
  {
    id: 5,
    name: "Pretty Arch",
    location: "UT",
    image: '/images/5.jpg',
    like: false,
  },
  {
    id: 6,
    name: "Devils Garden",
    location: "UT",
    image: '/images/6.jpg',
    like: false,
  },
  {
    id: 7,
    name: "Double Arch",
    location: "UT",
    image: '/images/7.jpg',
    like: false,
  },
  {
    id: 8,
    name: "Windows Sunrise",
    location: "UT",
    image: '/images/8.jpg',
    like: false,
  },
  {
    id: 9,
    name: "Arches Sunrise",
    location: "UT",
    image: '/images/9.jpg',
    like: false,
  },
  {
    id: 10,
    name: "Canyon",
    location: "UT",
    image: '/images/10.jpg',
    like: false,
  },
  {
    id: 11,
    name: "Hotspring",
    location: "WY",
    image: '/images/11.jpg',
    like: false,
  },
  {
    id: 12,
    name: "Fairy Falls",
    location: "WY",
    image: '/images/12.jpg',
    like: false,
  },
  {
    id: 13,
    name: "Lower Falls of the Yellowstone River",
    location: "WY",
    image: '/images/13.jpg',
    like: false,
  },
  {
    id: 14,
    name: "River",
    location: "WY",
    image: '/images/14.jpg',
    like: false,
  },
  {
    id: 15,
    name: "Upper Falls of the Yellowstone River",
    location: "WY",
    image: '/images/15.jpg',
    like: false,
  },
  {
    id: 16,
    name: "Beach Sunset",
    location: "FL",
    image: '/images/16.jpg',
    like: false,
  },
  {
    id: 17,
    name: "People Enjoying Beach Sunset",
    location: "FL",
    image: '/images/17.jpg',
    like: false,
  },
  {
    id: 18,
    name: "Mt. Pilchuck",
    location: "WA",
    image: '/images/18.jpg',
    like: false,
  },
  {
    id: 19,
    name: "Strawberry Point Sunset",
    location: "WA",
    image: '/images/19.jpg',
    like: false,
  },
  {
    id: 20,
    name: "Mt Rainier",
    location: "WA",
    image: '/images/20.jpg',
    like: false,
  },
  {
    id: 21,
    name: "Falls at Mt. Rainier",
    location: "WA",
    image: '/images/21.jpg',
    like: false,
  },
  {
    id: 22,
    name: "Grand Prismatic Spring From Afar",
    location: "WY",
    image: '/images/22.jpg',
    like: false,
  },
  {
    id: 23,
    name: "Flowers in Mt. Rainier National Park",
    location: "WA",
    image: '/images/23.jpg',
    like: false,
  },
]

export default mock;
